version: "4.60.0"

services:
  db:
    container_name: "workout_db"
    image: postgres:18-alpine
    volumes:
      - "./database/postgres-data:/var/lib/postgresql:rw"
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: 'postgres'
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'postgres'
    restart: unless-stopped